apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongod
spec:
  serviceName: mongodbsvc
  replicas: 3
  selector:
    matchLabels:
      app: mongoapp
  template:
    metadata:
      labels:
        app: mongoapp
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongod-container
        image: mongo:4.4
        command:
          - "mongod"
          - "--bind_ip"
          - "0.0.0.0"
          - "--replSet"
          - "MainRepSet"
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
          limits:
            cpu: 500m
            memory: 512Mi
        ports:
          - containerPort: 27017
        volumeMounts:
          - name: mongodb-persistent-storage-claim
            mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongodb-persistent-storage-claim
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongodbsvc
  labels:
    app: mongoapp
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    app: mongoapp
